[project]
name = "model-planning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.38.42",
    "circuit-tracer",
    "circuitsvis>=1.43.3",
    "indic-transliteration>=2.3.75",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "matplotlib>=3.10.3",
    "nltk>=3.9.1",
    "pandas>=2.3.0",
    "scikit-learn>=1.7.1",
    "seaborn>=0.13.2",
    "sentence-transformers>=5.0.0",
    "vllm>=0.9.1",
]

[tool.uv.sources]
circuit-tracer = { git = "https://github.com/safety-research/circuit-tracer.git" }
